package org.example.pizzeria.exception;

public class ErrorMessage {
    public static final String USER_NOT_FOUND = "User not found";
    public static final String INVALID_ID = "Invalid id";
    public static final String USER_ALREADY_EXIST = "User has already exist";
    public static final String DATA_IS_NULL = "Date is null";
    public static final String USER_REVIEW_NOT_FOUND = "User doesn`t have any reviews";
    public static final String USER_BLOCKED = "User can`t stay review";
    public static final String CANT_REVIEW_UPDATED = "User can`t update review";
    public static final String DOUGH_ALREADY_EXIST = "Dough already exist";
    public static final String INGREDIENT_ALREADY_EXIST = "Ingredient already exist";
    public static final String DOUGH_ALREADY_USE_IN_PIZZA = "Dough already use in pizzas recipe";
    public static final String INGREDIENT_ALREADY_USE_IN_PIZZA = "Ingredient already use in pizzas recipe";
    public static final String RECIPE_ALREADY_ORDERED = "This recipe already was in client order";
    public static final String FAVORITES_IS_EMPTY = "Favorites list is empty";

}
